language: elixir
git:
  depth: 1000
cache:
  directories:
    - _build
    - deps
services:
  - redis-server
addons:
  apt:
    packages:
      - docker-ce
elixir:
  - 1.8.1
otp_release:
  - 21.2.5
notifications:
  slack:
    rooms:
      - secure: "sLWOTNQfJHEATOoMKO9nd01AgOtd+eShyAhVikqssCGqazYreFi5sd4dGR5Q+tEeY5AAy4p7dEqB8wruoTwFyfkgHKYrc4tf7/1Uxf092thVnjDBj2+nLaOox/iqPvlpUWsPV30VBd0rrlZiyMh7EUBtINCbV026zPn9umTUQBZ297oYYAyuGq5IXKwnWVd4uixS62OXNnkUF5jijUDzcdXUrUN2fDzJmI7F26lvdiWj/EOoTwo4PwZqq+4CDi0VS1sgfguIlBayyDueiltFURdFhvrA7WRupVeypyCqra+1oDPH+DIeAJtN9nif57wsbGimxUmdevK/yvUi7b+BhDQUX0+fkeQ20EWMzI+2uv0It6jMumYybwRpL3AT2+FB5bbW9MEEU8gQ7/E8Ci/m2ABA4oUfXVvX3wyIANSafgOZ/ANZXoCtGSiSLJ4QQrtCeqG+sIJVT4y6hHrUlrDhZuOUdf6b0MNbYUqgiV7zYCk8JNx3cn+KDwisvwmrBaLi0mYs7ZkZGBZVGM6qH87ip7/JgSoVspR9dz2KmruCnitcaIsU67abH9Ns406LH2vqGWggIWenetBXnLrVOiDElq8y2miFwlphw2qe4uuFiyZXfTRaPdMPe20/VN5Wlr4dw08ln5BzhKpO9RZINh3eGUdrffxj/8cLcH8dpkUY+GI="
    on_success: always
env:
  global:
    - NO_ECTO_SETUP=true
    - MIX_ENV=test
    - DOCKER_NAMESPACE=edenlabllc
    - APPS='[{"app":"abac_api","chart":"abac-api","namespace":"abac","deployment":"api","label":"api"}]'
    - secure: "QSO4GUA8+/gBGcBb/kOHhwHfmvYoljqz8ZuP+E1gm2qrOic2rViTSoXhMgk1GOpEDLBUPzDk+k+dhUiEl13D7dVZo9FM+cQj6GylPQ9d2YWRpU7DmMcR6JlG2m1cgv1xHZUgbSFlg1w4BWKGIS/qv+bsXhCH+zkk1PYstWxptIwJqGAlEPZK8wCIJ4TaZ5RGpcnx8EufkmJaJjo2kuOmspzfzx7EbsK16bAmpey2jK7L2OZyW3FFmp9LH2sYC+jkbifETtMLkzL+kAeCLOb8SZX4jDXC+S3LT+w/qxYqggi3sox6TDK20QizUtuEDPYCY78qxLWzjIJLa2pKSzAId9U9Jndno7AbLVpYUzKeRK2UzcvjqbDFMPme9hSkQrMtj5GZTkIIW1y/a2QFsSjF5amKHNwgVOKjC6Zhrp+eHaTeK4Rc0T+EsGALzDkTKXj7cMPAtZ/cL4GVZCjIjPErW4DzAO0xVHd2Bwe2KVewJO6J1iaKxb/zOjMeYrXnjy+GbD9J2FLuBm7tA+kndxdUQn/NEkw2PPG7xSjOsX0p8LvzNpmNX9nRd7d/CBOMM9rOw4p/pEgdwnYHIUXSvyGivEOniUptPLFhRiJU1hM5BOnNvUH4cEDBJZ4rXIOOqfsngiEh71UZUwrlGsfAMhdkziL3VDHDibiQNAMLMMrpvDg="
    - secure: "nIXxC5zRbHpd2U6/rRU+t1qwrzhArWZZGb1SJOJ1XuKLZimxQh/J9AC8E1zSDdTNgH23GQZVOestBdNtBdKzAi9M2NKHj7CgnPummET91scbkbpgmO2pPkkSZMh082+jmMDoQOecB6U4t876VH0bjKEOksiqn17tW187PkHZR7BAiA2VLuL7aRiE4cp9gY4+V1u8e5NV+X7cuAvcVQ6IsJYyNbBjbTIWVn9weJA60u2T9n89HUGnoXGDbo6QmXkKq8KF3J1KynbNtOo9ALYezM+oconzQpdEdYAHmA4apNMqI6B0rzkLT/z+v42O8tz9WDfGHLkyQJQ2PKXksyj6gmCnHHKJHDsSqrhK1atuUraWGp+Ex8bxErpu+zAQHM6WpjavIny18cd2whDppRFoSvMJldoMgswZQ85PssuZLTIv0m2OTVQ0qWBw9ax0EmUugc3XhR4wuLprg5GGmzBjwBR2/AS6EjAwFehdRnBTGjE+GvUSZw5nKN9jxEIitRbgd+AeUANJtYI3tJJt5iJDkpuKYpNaN4UsnSLpeNyTtHj/x2HC6dFqeVOU6XI4Gb9q+NnKLceZmgld1Aop/UJW0Ec7vIqdrS0AuMM+lvOTNQk1no94CAp1Hb4psIXswEsURUlz0+9gWjBKEy+tTrVmej7jcnhqZYS4kN9m87DrTBs="
branches:
  except:
    - /[0-9]*\.[0-9]*\.[0-9]*/
before_install:
  - sudo apt-get install jq
  - curl -s https://raw.githubusercontent.com/edenlabllc/ci-utils/umbrella_v2/init-redis.sh -o init-redis.sh; sudo sh ./init-redis.sh
  - curl -s https://raw.githubusercontent.com/edenlabllc/ci-utils/umbrella_v2/install-mongodb.sh -o install-mongodb.sh; sudo sh ./install-mongodb.sh
  - curl -s https://raw.githubusercontent.com/edenlabllc/ci-utils/umbrella_v2/init-kafka.sh -o init-kafka.sh; sudo sh ./init-kafka.sh
    # create kafka topics
  - kafka/bin/kafka-topics.sh --create --partitions 1 --replication-factor 1 --zookeeper localhost:2181 --topic abac_logs

jobs:
  include:
    - stage: "test and build"
      name: "Run tests"
      script:
      - (curl -s https://raw.githubusercontent.com/edenlabllc/ci-utils/umbrella_v2/tests.sh -o tests.sh; bash ./tests.sh) || travis_terminate 1

    - stage: "test and build"
      name: "Api"
      # "Decrypting deploy key..."
      script:
      - openssl aes-256-cbc -K $encrypted_981a807ebf92_key -iv $encrypted_981a807ebf92_iv -in eHealth-8110bd102a69.json.enc -out eHealth-8110bd102a69.json -d
      - (curl -s https://raw.githubusercontent.com/edenlabllc/ci-utils/umbrella_v2/docker.sh -o docker.sh; bash ./docker.sh) || travis_terminate 1

    - stage: "test and build"
      name: "Abac logs Consumer"
      env:
      - APPS='[{"app":"abac_log_consumer","chart":"abac-api","namespace":"abac","deployment":"abac-logs-consumer","label":"abac-logs-consumer"}]'
      # "Decrypting deploy key..."
      script:
      - openssl aes-256-cbc -K $encrypted_981a807ebf92_key -iv $encrypted_981a807ebf92_iv -in eHealth-8110bd102a69.json.enc -out eHealth-8110bd102a69.json -d
      - (curl -s https://raw.githubusercontent.com/edenlabllc/ci-utils/umbrella_v2/docker.sh -o docker.sh; bash ./docker.sh) || travis_terminate 1
